#!/bin/bash

blk='\e[0;30m' red='\e[0;31m' grn='\e[0;32m' ylw='\e[0;33m'

blu='\e[0;34m' pur='\e[0;35m' cyn='\e[0;36m' wht='\e[0;37m'

clear

case "$1" in

	"")clear

printf "${blu}Welcome To Parrot Termux For Android\n"

printf "${red}> ${wht}https://github.com/wahasa/Parrot"

printf "\n\n"

printf "${ylw}• Parrot (Electro Ara)"

printf "\n\n"

printf "${blu}Name    ${red}: ${grn}Parrot5.3\n"

printf "${blu}Version ${red}: ${grn}5.3\n"

printf "${blu}Status  ${red}: ${grn}Latest\n"

printf "${blu}Rootfs  ${red}: ${grn}Armhf,Arm64,Amd64"

printf "\n\n"

	;;

        "Parrot5.3")

wget https://raw.githubusercontent.com/wahasa/Parrot/main/Install/parrot.sh ; chmod +x parrot.sh ; bash parrot.sh

        ;;

        *)

	bash Install

        ;;

esac
